version: "3"

services:
  pi:
    build: ./exporter/.
    image: pi:latest
    container_name: pi
    environment:
      - ROOT_FS=/rootfs
    volumes:
      - /:/rootfs
    ports:
      - "5000:5000"
    restart: unless-stopped
