version: "3"

services:
  pi:
    build: /exporter/.
    image: pi:latest
    container_name: pi
    environment:
      - ROOT_FS=/rootfs
    volumes:
      - /:/rootfs
    ports:
      - "5000:5000"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.30.3
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/prom:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped
    depends_on:
      - pi

  graphana:
    image: grafana/grafana:8.2.1
    container_name: graphana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin_pass
      - GF_USERS_ALLOW_SIGN_UP=true
    volumes:
      - ./grafana/grafana-storage:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards:/etc/grafana/dashboards
    restart: unless-stopped
    depends_on:
      - prometheus
      - pi
