global:
  scrape_interval: 15s 

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'raspberry-1'
    metrics_path: /node/1/metrics
    scrape_interval: 5s
    static_configs:
      - targets: ['wutterfly.com']
