{
 "title": "Raspberry",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "format": "h",
   "valueName": "current",
   "targets": [
    {
     "expr": "(system_time{node=\"1\"} - boot_time{node=\"1\"} ) /  3600"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "cpu_cores{type=\"physical\" ,node=\"1\"}"
    }
   ]
  },
  {
   "title": "Total Storage",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 9, "y": 0 },
   "format": "decgbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "disk_usage{mount=\"/rootfs\" ,type=\"total\" ,node=\"1\"} / 1000000000"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 13, "y": 0 },
   "format": "decgbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "memory_usage{type=\"total\" ,node=\"1\"}  / 1000000000"
    }
   ]
  },
  {
   "title": "TCP Connections",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "tcp_connections{node=\"1\"}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "cpu_temperature{node=\"1\"}"
    }
   ]
  },
  {
   "title": "Used Disk Storage",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 2 },
   "targets": [
    {
     "expr": "disk_usage{mount=\"/rootfs\" ,type=\"used\" ,node=\"1\"}  / 1000000000",
     "legendFormat": "Used Storage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 2 },
   "targets": [
    {
     "expr": "memory_usage{type=\"used\" ,node=\"1\"} / 1000000000"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "cpu_usage{node=\"1\"}"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 5 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "memory_usage{type=\"used\" ,node=\"1\"} /  1000000000"
    }
   ]
  }
 ]
}