version: "3"

services:
  prometheus:
    image: prom/prometheus:v2.30.3
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prom:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      moni_ipv6:
        ipv6_address: 2001:638:408:200:FC36:dddd::11
    restart: unless-stopped

  graphana:
    image: grafana/grafana:6.5.0
    container_name: graphana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin_pass
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      moni_ipv6:
        ipv6_address: 2001:638:408:200:FC36:dddd::19
    restart: unless-stopped

networks:
  moni_ipv6:
    external: true
    name: moni_ipv6
